export const SET_AUTH_STATE = 'AUTH/SET_AUTH_STATE';
export const SET_CURRENT_USER = 'AUTH/SET_CURRENT_USER';
export const SET_LOADING_STATUS = 'AUTH/SET_LOADING_STATUS';

export const SET_CATEGORIES = 'CATEGORIES/SET_CATEGORIES';
export const SET_INCOMES_CATEGORIES = 'CATEGORIES/SET_INCOMES_CATEGORIES';
export const SET_EXPENSES_CATEGORIES = 'CATEGORIES/SET_EXPENSES_CATEGORIES';
